config-version: 2

name: "jaffle_platform"
version: "1.0.0"
require-dbt-version: ">=1.9.0"

profile: "local"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Europe/Paris" # Adapté pour la France

models:
  jaffle_platform:
    +schema: main # Schéma par défaut pour tous les modèles
    marts:
      +materialized: table # Les modèles marts sont matérialisés comme des tables
    stg:
      +materialized: view # Les modèles staging sont matérialisés comme des vues
