version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: jaffle_postgres
    environment:
      POSTGRES_USER: jaffle
      POSTGRES_PASSWORD: jaffle
      POSTGRES_DB: jaffle_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
