version: 2

models:
  - name: orders
    config:
      freshness_policy:
        maximum_lag_seconds: 3600 # 1 heure
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: customers
    config:
      freshness_policy:
        maximum_lag_seconds: 3600 # 1 heure
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: order_items
    config:
      freshness_policy:
        maximum_lag_seconds: 3600 # 1 heure
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
