local:
  outputs:
    prod:
      type: postgres
      host: localhost
      user: jaffle
      password: jaffle
      port: 5432
      dbname: jaffle_db
      schema: main
      threads: 1

  target: prod
